module.exports = {
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  NAME_REQUIRED: 'YOU_MUST_PASS_A_NAME',
  BIRTHDATE_REQUIRED: 'YOU_MUST_PASS_A_BIRTHDATE',
  ROLE_REQUIRED: 'YOU_MUST_PASS_A_ROLE',
  DESCRIPTION_REQUIRED: 'YOU_MUST_PASS_A_DESCRIPTION',
  MEMBER_ID_REQUIRED: 'MEMBER_ID_REQUIRED',
  TEAM_MEMBER_ID_REQUIRED: 'TEAM_MEMBER_ID_REQUIRED',
  TEAM_ID_REQUIRED: 'TEAM_ID_REQUIRED',
  ROLE_NOT_ALLOWED: 'ROLE_NOT_ALLOWED',
};